import { AcDbDatabase, AcDbEntity } from '@mlightcad/data-model'

import { AcTpPartIdParts, parsePartId } from './AcTpPartId'
import { SEED_ROLES } from './AcTpSeed'
import { readSemanticTag, SEMANTIC_TAG_APP_ID } from './AcTpSemanticTag'

/**
 * The read half of `ctx`.
 *
 * Templates tag what they draw; this turns a tagged database back into
 * something that can be reasoned about — what parts exist, which one is
 * which, and what values define them. Natural-language editing needs this
 * before it needs anything else: an assistant cannot decide *where* to edit
 * from a list of line segments.
 *
 * The output is plain data with no dependency on Vue, Element Plus or the
 * viewer, so the AI proxy can serialise it and send it as-is.
 */

/** Axis-aligned extent of a part, in drawing units. */
export interface AcTpBounds {
  minX: number
  minY: number
  maxX: number
  maxY: number
}

/** One addressable part of a drawing. */
export interface AcTpPartSummary {
  /** Dictionary key — `lan_can`, `ban_mat_cau`. */
  role: string
  /** Vietnamese display name for the role, when the role is a known one. */
  roleLabel?: string
  partId: string
  /** Parsed out of `partId`; absent when the id follows no known scheme. */
  side?: AcTpPartIdParts['side']
  ordinal?: number
  /** Layers the part's entities sit on. More than one is legal but unusual. */
  layers: string[]
  entityCount: number
  /**
   * Ids of the entities that make up this part.
   *
   * Carried so a caller can select or modify the part without walking the
   * database again — and, more importantly, without matching on geometry.
   * Re-finding a part by coordinates is exactly the fragile addressing the
   * semantic tag exists to replace.
   */
  objectIds: string[]
  bounds?: AcTpBounds
  /** Values the template recorded for this part, merged across its entities. */
  params?: Record<string, number | string | boolean>
}

/**
 * Whether a drawing can be addressed semantically at all.
 *
 * The three states are kept apart deliberately. `untagged` is not "nothing
 * found" — it means the question cannot be asked of this drawing, and an
 * assistant that conflates the two will happily report "no rail here" about a
 * DWG that is all rail.
 */
export type AcTpDigestStatus =
  /** Tagged by a template; every part is addressable. */
  | 'tagged'
  /** No semantic tags at all — typically a drawing imported from DWG. */
  | 'untagged'
  /** Tags present but none readable: written by a newer or broken schema. */
  | 'schema-mismatch'

export interface AcTpDrawingDigest {
  status: AcTpDigestStatus
  /** Templates that contributed parts. Normally exactly one. */
  templateIds: string[]
  parts: AcTpPartSummary[]
  /** Entities carrying no readable tag — hand-drawn or imported geometry. */
  untaggedEntityCount: number
}

/** Ids that could not be parsed sort last, then by role, side, ordinal. */
function comparePart(a: AcTpPartSummary, b: AcTpPartSummary): number {
  if (a.role !== b.role) return a.role.localeCompare(b.role)
  const sideRank = (s?: string) => (s === 'trai' ? 0 : s === 'phai' ? 1 : 2)
  if (sideRank(a.side) !== sideRank(b.side)) {
    return sideRank(a.side) - sideRank(b.side)
  }
  return (a.ordinal ?? 0) - (b.ordinal ?? 0)
}

function growBounds(
  into: AcTpBounds | undefined,
  entity: AcDbEntity
): AcTpBounds | undefined {
  // Not every entity type reports extents, and a template is not wrong for
  // using one that does not. A part with no measurable entity simply has no
  // bounds rather than bounds of (0,0,0,0), which would place it at origin.
  let box
  try {
    box = entity.geometricExtents
  } catch {
    return into
  }
  if (!box?.min || !box?.max) return into

  const next: AcTpBounds = {
    minX: box.min.x,
    minY: box.min.y,
    maxX: box.max.x,
    maxY: box.max.y
  }
  if (!into) return next
  return {
    minX: Math.min(into.minX, next.minX),
    minY: Math.min(into.minY, next.minY),
    maxX: Math.max(into.maxX, next.maxX),
    maxY: Math.max(into.maxY, next.maxY)
  }
}

/**
 * Reads a database into a part-level description.
 *
 * @param db - Database to read. Only model space is walked; paper-space
 * layouts hold presentation, not structure.
 * @param roleLabels - Role → Vietnamese name. Defaults to the seed list;
 * pass the standards dictionary once Epic 2 supplies one.
 */
export function readDrawingDigest(
  db: AcDbDatabase,
  roleLabels: Readonly<Record<string, string>> = SEED_ROLES
): AcTpDrawingDigest {
  const byPartId = new Map<string, AcTpPartSummary>()
  const templateIds = new Set<string>()
  let untaggedEntityCount = 0
  let sawXData = false

  for (const entity of db.tables.blockTable.modelSpace.newIterator()) {
    const tag = readSemanticTag(entity)
    if (!tag) {
      // Separates "no tag" from "a tag we cannot read": the second one means
      // the drawing *was* generated by a template, just not one this build
      // understands, and saying "untagged" about it would be a lie.
      if (entity.getXData?.(SEMANTIC_TAG_APP_ID)) sawXData = true
      untaggedEntityCount++
      continue
    }

    templateIds.add(tag.templateId)

    let part = byPartId.get(tag.partId)
    if (!part) {
      const parsed = parsePartId(tag.partId, tag.role)
      part = {
        role: tag.role,
        ...(roleLabels[tag.role] ? { roleLabel: roleLabels[tag.role] } : {}),
        partId: tag.partId,
        ...(parsed?.side ? { side: parsed.side } : {}),
        ...(parsed?.ordinal !== undefined ? { ordinal: parsed.ordinal } : {}),
        layers: [],
        entityCount: 0,
        objectIds: []
      }
      byPartId.set(tag.partId, part)
    }

    part.entityCount++
    if (entity.objectId) part.objectIds.push(entity.objectId)
    if (entity.layer && !part.layers.includes(entity.layer)) {
      part.layers.push(entity.layer)
    }
    const bounds = growBounds(part.bounds, entity)
    if (bounds) part.bounds = bounds
    if (tag.params) {
      part.params = { ...(part.params ?? {}), ...tag.params }
    }
  }

  const parts = [...byPartId.values()].sort(comparePart)
  parts.forEach(part => part.layers.sort())

  const status: AcTpDigestStatus =
    parts.length > 0 ? 'tagged' : sawXData ? 'schema-mismatch' : 'untagged'

  return {
    status,
    templateIds: [...templateIds].sort(),
    parts,
    untaggedEntityCount
  }
}

/**
 * Finds the parts a phrase could be referring to.
 *
 * Deliberately does no language understanding — that belongs to the assistant
 * with the standards dictionary in hand. This narrows an already-resolved
 * role, plus optional side and ordinal, to concrete parts, and returning an
 * array rather than a best guess is the point: two matches means the request
 * was ambiguous and something must ask rather than pick.
 */
export function findParts(
  digest: AcTpDrawingDigest,
  query: { role: string; side?: AcTpPartIdParts['side']; ordinal?: number }
): AcTpPartSummary[] {
  return digest.parts.filter(
    part =>
      part.role === query.role &&
      (query.side === undefined || part.side === query.side) &&
      (query.ordinal === undefined || part.ordinal === query.ordinal)
  )
}
