import type {
  AcTpDrawContext,
  AcTpParamValues,
  AcTpTemplate
} from '@mlightcad/cad-template-sdk'

import { renderTemplatePreview } from '../src/templatePreview'

/** Builds a template literal without repeating the cast at every call site. */
const templateOf = (
  meta: Partial<AcTpTemplate['meta']>,
  params: AcTpTemplate['params'],
  generate: AcTpTemplate['generate']
): AcTpTemplate =>
  ({
    meta: { version: '1.0.0', category: 'cau', ...meta },
    params,
    generate
  }) as AcTpTemplate

/**
 * The thumbnail is generated by running the template, so these check that the
 * generated picture matches the geometry rather than that some SVG came out.
 */
describe('template thumbnails', () => {
  test('the drawn shapes appear in the SVG', () => {
    const preview = renderTemplatePreview(
      templateOf(
        { id: 'thu', name: 'Thử' },
        [{ key: 'B', label: 'B', type: 'number', default: 4 }],
        (ctx: AcTpDrawContext, values: AcTpParamValues) => {
          const half = Number(values.B) / 2
          ctx.polyline({
            role: 'ban_mat_cau',
            partId: 'ban_mat_cau',
            closed: true,
            points: [
              { x: -half, y: 0, z: 0 },
              { x: half, y: 0, z: 0 },
              { x: half, y: -1, z: 0 },
              { x: -half, y: -1, z: 0 }
            ]
          })
          ctx.circle({
            role: 'ong_thoat_nuoc',
            partId: 'ong_thoat_nuoc_01',
            center: { x: 0, y: -2, z: 0 },
            radius: 0.5
          })
        }
      )
    )

    expect(preview.svg).toContain('<polygon')
    expect(preview.svg).toContain('<circle')
    // Defaults were used: B = 4 puts the slab edge at ±2.
    expect(preview.svg).toContain('-2,0 2,0')
  })

  test('a template drawing nothing says so instead of showing an empty box', () => {
    const preview = renderTemplatePreview(
      templateOf({ id: 'rong', name: 'Rỗng' }, [], () => undefined)
    )
    expect(preview.svg).toBeUndefined()
    expect(preview.reason).toContain('không vẽ hình nào')
  })

  test('a template whose defaults throw yields a reason, not an exception', () => {
    // The picker still has to render the card, or the engineer cannot tell
    // which template is the broken one.
    const preview = renderTemplatePreview(
      templateOf({ id: 'hong', name: 'Hỏng' }, [], () => {
        throw new Error('Thiếu thông số bắt buộc')
      })
    )
    expect(preview.svg).toBeUndefined()
    expect(preview.reason).toContain('Thiếu thông số')
  })

  test('an async template is declined rather than rendered half-drawn', () => {
    const preview = renderTemplatePreview({
      meta: {
        id: 'bat_dong_bo',
        version: '1.0.0',
        name: 'Async',
        category: 'cau'
      },
      params: [],
      generate: async () => undefined
    } as never)
    expect(preview.reason).toContain('bất đồng bộ')
  })
})
